CC := gcc
Target := address_book
Source := $(wildcard src/*.c)
Objs := $(patsubst %.c,%.o,$(Source))
Modules += main choose delete insert is_malloc my_strcpy create display input interface my_strcmp output search
Allobjs := $(addsuffix /src/*.o,$(Modules))
